"""ChimeraX model of one traced filament set: a tube surface per filament (in its instance colour) with arrowheads
showing its direction (point order: what "reverse" flips), and, while editing, the control points as instanced
spheres.

The curves live in a ``FilamentEditSession`` (copick-shared-ui); every edit is regenerated by copick core, and this
model only redraws from ``session.polylines()`` / ``session.all_controls()``. Coordinates are Angstrom, the frame of
the tomograms.

Deliberately not a MarkerSet: ChimeraX's ``mark plane`` mode places markers into the first MarkerSet it finds, which
would collide with ArtiaX particle lists.
"""

from typing import Dict, Iterable, Optional, Set

import numpy as np
from chimerax.core.models import Model, Surface
from copick_shared_ui.util.filaments import polyline_tangents
from copick_shared_ui.util.instances import instance_colors

DEFAULT_RADIUS = 50.0
CIRCLE_SUBDIVISIONS = 12
#: Control points are drawn this much wider than the widest tube, so they stand out of it.
HANDLE_OVER_TUBE = 2.0
#: ... and at least this many tomogram steps (voxels) in radius.
HANDLE_MIN_STEPS = 2.5
#: The active filament's handles are drawn this much larger (and white).
ACTIVE_HANDLE_SCALE = 1.3
#: Direction arrowheads, relative to the tube radius; a second arrowhead mid-filament on filaments longer than
#: ``ARROW_MID_MIN_LENGTH`` arrowhead lengths (so the direction shows when the end is outside the slab).
ARROW_RADIUS = 2.4
ARROW_LENGTH = 6.0
ARROW_MID_MIN_LENGTH = 8.0


class FilamentSetModel(Model):
    """Tubes for the filaments of one ``FilamentEditSession``."""

    def __init__(self, session, edit_session, tube_scale: float = 0.5):
        name = f"{edit_session.object_name} filaments ({edit_session.user_id}/{edit_session.session_id})"
        Model.__init__(self, name, session)
        self.edit_session = edit_session
        self.tube_scale = float(tube_scale)
        self._tubes: Dict[int, Surface] = {}
        self._controls: Optional[Surface] = None
        self._handle_radius: Optional[float] = None
        self._hidden: Set[int] = set()
        self.show_controls = False

    # ----------------------------------------------------------------------------------------------------------------
    # Appearance
    # ----------------------------------------------------------------------------------------------------------------

    @property
    def base_rgba(self) -> np.ndarray:
        obj = self.edit_session.object
        color = getattr(obj, "color", None) or (255, 255, 255, 255)
        return np.asarray(color, dtype=np.uint8)[:4]

    @property
    def radius(self) -> float:
        return float(self.edit_session.radius or DEFAULT_RADIUS)

    def tube_radius(self, instance_id: int) -> float:
        f = self.edit_session.filaments.get(instance_id)
        r = getattr(f, "radius", None) if f is not None else None
        return float(r or self.radius) * self.tube_scale

    def handle_radius(self) -> float:
        """Radius of the control-point spheres: wider than the tubes, so they are visible on them."""
        tubes = [self.tube_radius(i) for i in self.edit_session.filaments] or [self.radius * self.tube_scale]
        return max(HANDLE_OVER_TUBE * max(tubes), HANDLE_MIN_STEPS * self.edit_session.step)

    def color_of(self, instance_id: int) -> np.ndarray:
        return instance_colors([instance_id], self.base_rgba, dtype=np.uint8)[0]

    # ----------------------------------------------------------------------------------------------------------------
    # Drawing
    # ----------------------------------------------------------------------------------------------------------------

    def redraw(self, ids: Optional[Iterable[int]] = None) -> None:
        """Rebuild the tubes of ``ids`` (default all), drop tubes of deleted filaments, redraw the controls."""
        lines = self.edit_session.polylines()
        for instance_id in list(self._tubes):
            if instance_id not in lines:
                self._tubes.pop(instance_id).delete()
        for instance_id in lines if ids is None else [i for i in ids if i in lines]:
            self._draw_tube(instance_id, lines[instance_id])
        for instance_id in [i for i in (ids or []) if i not in lines and i in self._tubes]:
            self._tubes.pop(instance_id).delete()
        self._draw_controls()

    def _draw_tube(self, instance_id: int, points: np.ndarray) -> None:
        from chimerax.surface.tube import tube_through_points

        pts = np.asarray(points, dtype=np.float32).reshape(-1, 3)
        if len(pts) < 2:
            return
        tangents = polyline_tangents(pts).astype(np.float32)
        radius = self.tube_radius(instance_id)
        va, na, ta = tube_through_points(pts, tangents, radius, CIRCLE_SUBDIVISIONS)
        va, na, ta = _with_arrowheads(va, na, ta, pts, radius)
        surf = self._tubes.get(instance_id)
        if surf is None or surf.deleted:
            surf = Surface(f"filament {instance_id}", self.session)
            self.add([surf])
            self._tubes[instance_id] = surf
        surf.set_geometry(va, na, ta)
        surf.color = self.color_of(instance_id)
        surf.display = instance_id not in self._hidden
        surf.copick_filament_id = instance_id

    def _draw_controls(self) -> None:
        from chimerax.geometry import Place, Places
        from chimerax.surface import sphere_geometry2

        controls = {i: c for i, c in self.edit_session.all_controls().items() if len(c)} if self.show_controls else {}
        controls = {i: c for i, c in controls.items() if i not in self._hidden}
        if not controls:
            if self._controls is not None and not self._controls.deleted:
                self._controls.display = False
            return
        r = self.handle_radius()
        if self._controls is None or self._controls.deleted:
            self._controls = Surface("control points", self.session)
            self.add([self._controls])
            self._handle_radius = None
        if self._handle_radius != r:  # the radius follows the tubes (filament radii, tube scale)
            va, na, ta = sphere_geometry2(200)
            self._controls.set_geometry((va * r).astype(np.float32), na.astype(np.float32), ta)
            self._handle_radius = r
        ids = np.concatenate([np.full(len(c), i) for i, c in controls.items()])
        xyz = np.concatenate(list(controls.values()))
        active = self.edit_session.active_id
        places = []
        for i, p in zip(ids, xyz, strict=True):
            k = ACTIVE_HANDLE_SCALE if i == active else 1.0
            places.append(Place(axes=np.eye(3) * k, origin=p))
        self._controls.positions = Places(places)
        colors = instance_colors(ids, self.base_rgba, dtype=np.uint8)
        colors[ids == active] = (255, 255, 255, 255)  # the active filament's handles are white
        self._controls.colors = colors
        self._controls.display = True

    # ----------------------------------------------------------------------------------------------------------------
    # Visibility
    # ----------------------------------------------------------------------------------------------------------------

    def set_visible_ids(self, ids: Iterable[int]) -> None:
        ids = {int(i) for i in ids}
        self._hidden = set(self._tubes) - ids
        for instance_id, surf in self._tubes.items():
            surf.display = instance_id in ids
        self._draw_controls()

    def set_show_controls(self, show: bool) -> None:
        self.show_controls = bool(show)
        self._draw_controls()

    def all_control_points(self):
        """``[(instance_id, index, xyz)]`` of every control point (for picking)."""
        out = []
        for instance_id, cps in self.edit_session.all_controls().items():
            for k, p in enumerate(cps):
                out.append((instance_id, k, p))
        return out


def _arrowhead_places(points: np.ndarray, length: float) -> list:
    """(base point, unit direction) of the arrowheads of a polyline: at its end and, if it is long, at its middle."""
    seg = np.linalg.norm(np.diff(points, axis=0), axis=1)
    total = float(seg.sum())
    if total <= 0:
        return []
    end_dir = points[-1] - points[-2]
    places = [(points[-1] - 0.25 * length * end_dir / np.linalg.norm(end_dir), end_dir)]
    if total > ARROW_MID_MIN_LENGTH * length:
        s = np.concatenate([[0.0], np.cumsum(seg)])
        k = int(np.clip(np.searchsorted(s, total / 2), 1, len(points) - 1))
        f = (total / 2 - s[k - 1]) / max(seg[k - 1], 1e-9)
        places.append((points[k - 1] + f * (points[k] - points[k - 1]), points[k] - points[k - 1]))
    return [(base, d / np.linalg.norm(d)) for base, d in places if np.linalg.norm(d) > 0]


def _with_arrowheads(va, na, ta, points: np.ndarray, tube_radius: float):
    """Add direction arrowheads (cones pointing along the filament) to a tube's geometry."""
    from chimerax.geometry import translation, vector_rotation
    from chimerax.surface import cone_geometry

    length = ARROW_LENGTH * tube_radius
    cva, cna, cta = cone_geometry(radius=ARROW_RADIUS * tube_radius, height=length, nc=CIRCLE_SUBDIVISIONS * 2)
    parts_v, parts_n, parts_t, offset = [va], [na], [ta], len(va)
    for base, direction in _arrowhead_places(np.asarray(points, dtype=float), length):
        rot = vector_rotation((0, 0, 1), tuple(direction))
        place = translation(tuple(base + 0.5 * length * direction)) * rot
        parts_v.append(place.transform_points(cva).astype(np.float32))
        parts_n.append(rot.transform_vectors(cna).astype(np.float32))
        parts_t.append((cta + offset).astype(ta.dtype))
        offset += len(cva)
    return np.concatenate(parts_v), np.concatenate(parts_n), np.concatenate(parts_t)
